name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe it.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered?
      placeholder: I also thought about...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - Quest Tracking
        - Storyline / 1.0
        - Collector Items
        - Prestige System
        - Achievements
        - Hideout
        - UI/UX
        - Data / API
        - Profiles / Data Management
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (in your opinion)
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my experience
        - Important for my workflow
        - Critical / Blocking

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: If applicable, add mockups, screenshots, or examples
      placeholder: Drag and drop images here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the feature request
